### PR TITLE
JBOSGI 2.3.0.Final = WFLY 8.2.0.Final + Java SE 8

### PR DESCRIPTION
**Pull request by arcivanov**

### CODE REVIEW

**Comment by tdiesler** [comment]
Why is this updating to 4.0.3.Final?

**Comment by arcivanov** [comment]
All current components of JBOSGi underwent refactoring wrt jbosgi-parent to cut down on dependency refactoring to:

1. Slim down downstream POMs and allow common dependencies to be controlled from jbosgi-parent.
2. Cut down on dependency and plugin replication.
3. Align external dependency versions with WildFly server releases.
4. Aligning jbosgi-parent to a WildFly release allows maintaining several branched versions of the jbosgi-parent at the top of hierarchies tracking different releases of WildFly (e.g. 8.x and 9.x).
5. Easier common control for plugin versions.

Other changes across the repos include removal of deprecation, and fixes to some unit tests.

**Comment by arcivanov** [comment]
All CR, beta and other non-final versions were bumped to nearest Final as well.

**Comment by tdiesler** [comment]
Congratulation for your [jbosgi-2.3.0](http://ivanov.biz/2015/jbosgi-for-wildfly-8-2-released/) release - I didn't realize that before. I'm happy to hand over the OSGi effort for WildFly to you.

**Comment by arcivanov** [comment]
Thanks, Thomas! That works for me if it works for you.

**Comment by tdiesler** [comment]
For [wildfly-camel](https://fabric8-ci.fusesource.com/job/wildfly-camel-pullreq/) I use this script with ghprb to automatically fast forward successful PRs

```
echo Log result of the original merge
git log --max-count=16 --oneline
echo 

echo Checkout target branch and pull from origin
git checkout -f $ghprbTargetBranch
git fetch origin $ghprbTargetBranch
git reset --hard FETCH_HEAD
echo Log target branch at origin
git log --max-count=16 --oneline
echo 

echo Rebase actual commit on target branch
BRANCH_PREFIX=buildBranch
BRANCH_NAME=$BRANCH_PREFIX#$BUILD_NUMBER
git checkout -b $BRANCH_NAME $ghprbActualCommit
rm -rf .git/rebase-apply
git rebase $ghprbTargetBranch
echo Log source branch after rebase
git log --max-count=16 --oneline
echo 

echo Fast forward the target branch
git checkout $ghprbTargetBranch
git merge --ff-only $BRANCH_NAME
git branch | grep $BRANCH_PREFIX | xargs git branch -D
echo Log target branch after rebase
git log --max-count=16 --oneline
git status
echo 
```

**Comment by arcivanov** [comment]
Thanks Thomas! I do not generally automerge successful pull requests since they need to be reviewed by hand anyway, but this is a great script to use and I'll add it to my library.

**Comment by tdiesler** [comment]
The idea is that you only do "ok to test" after a trusted engineer did the review

**Comment by arcivanov** [comment]
You could do that. 

But one of the features of the PR is that it can be repeatedly updated. If the build farm is scaleable and the full build/test cycle is cheap, it's more advantageous to allow developers to use PRs for intermediate staging as well (WFLY does use a very similar approach and so does Jenkins CI) or even to allow developers to outsource building to PR Builder entirely (really saves a lot of time).

The corollary to the above is that the developers submitting the PRs are not the same ones that review and merge them or that the developers are reliable.

**Pull request closed without merging**
